site_name: PsycholWiki
theme:
    name: material
    language: zh
    favicon: images/favicon.png
site_author: WuMoe LLC
site_description: 给病友的参考指南
repo_url: https://github.com/project-psychol/psychol-wiki

nav:
  - '首页': 'index.md'
  - '疾病':
    - '双相情感障碍': 'diseases/bipolar_disorder.md'
    - '抑郁障碍': 'diseases/depression.md'
