site_name: PsycholWiki
theme: material
site_author: WuMoe LLC
site_description: 给病友的参考指南
repo_url: https://github.com/project-psychol/psychol-wiki

nav:
  - '首页': 'index.md'
  - '疾病':
    - '双相情感障碍': 'docs/bipolar_disorder.md'
